name: Test Package

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test Sessions Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.0

      - name: Build Redis
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/redis/Dockerfile
          load: true
          tags: my-redis:latest

      - name: Run Redis
        run: |
          docker run -d --name redis -p 6379:6379 --env REDIS_PASSWORD=redis my-redis:latest

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Workspace Dependencies
        run: pnpm i --frozen-lockfile

      - name: Wait for Redis
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Test Package Types
        run: pnpm run test:types

      - name: Test Package Unit Tests
        run: pnpm run test:lib
