name: Test Package

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test Sessions Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.0

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Workspace Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Packages
        run: pnpm run build

      - name: Test Packages and Template
        run: pnpm run test
